import RPi.GPIO as gpio
import time 

gpio.setwarnings(False)

l1 = 4
l2 = 9
l3 = 25
l4 = 8
l5 = 7
l6 = 26
l7 = 12

l8 = 3
l9 = 14
l10 = 15

def init():
    gpio.setmode(gpio.BCM)
    gpio.setup(l1,gpio.OUT)
    gpio.setup(l2,gpio.OUT)
    gpio.setup(l3,gpio.OUT)
    gpio.setup(l4,gpio.OUT)
    gpio.setup(l5,gpio.OUT)
    gpio.setup(l6,gpio.OUT)
    gpio.setup(l7,gpio.OUT)
    gpio.setup(l8,gpio.OUT)
    gpio.setup(l9,gpio.OUT)
    gpio.setup(l10,gpio.OUT)
    gpio.output(l8,0)

def kapa():
    init()
    gpio.output(l1,0)
    gpio.output(l2,0)
    gpio.output(l3,0)
    gpio.output(l4,0)
    gpio.output(l5,0)
    gpio.output(l6,0)
    gpio.output(l7,0)
    gpio.output(l8,0)
    gpio.output(l9,0)
    gpio.output(l10,0)
    gpio.cleanup()

def l12345(af,sf,df,ff,gf,tf):
    init()
    gpio.output(l1,af)
    gpio.output(l2,sf)
#    gpio.output(l3,df)
    gpio.output(l4,ff)
    gpio.output(l5,gf)
    time.sleep(tf)
    kapa()
    gpio.cleanup()

def l678910(af,sf,df,ff,gf,tf):
    init()    
    gpio.output(l6,af)
    gpio.output(l7,sf)
    gpio.output(l8,df)
    gpio.output(l9,ff)
    gpio.output(l10,gf)
    time.sleep(tf)
    kapa()
    gpio.cleanup()

def solakayan(tf):
    init()
    gpio.output(l1,1)
    time.sleep(tf)
    gpio.output(l1,0)
    gpio.output(l2,1)
    time.sleep(tf)
    gpio.output(l2,0)
    gpio.output(l3,1)
    time.sleep(tf)
    gpio.output(l3,0)
    gpio.output(l4,1)
    time.sleep(tf)
    gpio.output(l4,0)
    gpio.output(l5,1)
    time.sleep(tf)
    gpio.output(l5,0)
    gpio.output(l6,1)
    time.sleep(tf)
    gpio.output(l6,0)
    gpio.output(l7,1)
    time.sleep(tf)
    gpio.output(l7,0)
    gpio.output(l8,1)
    time.sleep(tf)
    gpio.output(l8,0)
    gpio.output(l9,1)
    time.sleep(tf)
    gpio.output(l9,0)
    gpio.output(l10,1)
    time.sleep(tf)
    gpio.output(l10,0)
    gpio.cleanup()

def sagakayan(tf):
    init()
    gpio.output(l10,1)
    time.sleep(tf)
    gpio.output(l10,0)
    gpio.output(l9,1)
    time.sleep(tf)
    gpio.output(l9,0)
    gpio.output(l8,1)
    time.sleep(tf)
    gpio.output(l8,0)
    gpio.output(l7,1)
    time.sleep(tf)
    gpio.output(l7,0)
    gpio.output(l6,1)
    time.sleep(tf)
    gpio.output(l6,0)
    gpio.output(l5,1)
    time.sleep(tf)
    gpio.output(l5,0)
    gpio.output(l4,1)
    time.sleep(tf)
    gpio.output(l4,0)
    gpio.output(l3,1)
    time.sleep(tf)
    gpio.output(l3,0)
    gpio.output(l2,1)
    time.sleep(tf)
    gpio.output(l2,0)
    gpio.output(l1,1)
    time.sleep(tf)
    gpio.output(l1,0)
    gpio.cleanup()

def ilerikayan(tf):
    init()
    gpio.output(l1,1)
    gpio.output(l10,1)
    time.sleep(tf)
    gpio.output(l1,0)
    gpio.output(l10,0)
    gpio.output(l2,1)
    gpio.output(l9,1)
    time.sleep(tf)
    gpio.output(l2,0)
    gpio.output(l9,0)
    gpio.output(l3,1)
    gpio.output(l8,1)
    time.sleep(tf)
    gpio.output(l3,0)
    gpio.output(l8,0)
    gpio.output(l4,1)
    gpio.output(l7,1)
    time.sleep(tf)
    gpio.output(l4,0)
    gpio.output(l7,0)
    gpio.output(l5,1)
    gpio.output(l6,1)
    time.sleep(tf)
    gpio.output(l5,0)
    gpio.output(l6,0)

def gerikayan(tf):
    init()
    gpio.output(l5,0)
    gpio.output(l6,0)
    time.sleep(tf)
    gpio.output(l5,0)
    gpio.output(l6,0)
    gpio.output(l4,1)
    gpio.output(l7,1)
    time.sleep(tf)
    gpio.output(l4,0)
    gpio.output(l7,0)
    gpio.output(l3,1)
    gpio.output(l8,1)
    time.sleep(tf)
    gpio.output(l3,0)
    gpio.output(l8,0)
    gpio.output(l2,1)
    gpio.output(l9,1)
    time.sleep(tf)
    gpio.output(l2,0)
    gpio.output(l9,0)
    gpio.output(l1,1)
    gpio.output(l10,1)
    time.sleep(tf)
    gpio.output(l1,0)
    gpio.output(l10,0)


kapa()

